/*
 * Created on Feb 8, 2005
 */
package org.adammarker.sloth;

import org.eclipse.swt.graphics.RGB;

/**
 * @author Adam Marker Feb 8, 2005
 */
public interface LSL {
    
    //TODO:  figure out where these declarations should go.
    // these are just the defaults .... others will come from prefs.
    // all will need disposing. (image, color, font)


    static final RGB KEYWORD_RGB = new RGB(134,37,84) ;
    static final RGB EVENT_RGB = new RGB(13,84,134) ;
    static final RGB TYPE_RGB = new RGB(36,84,36) ;
    static final RGB STRING_RGB = new RGB(13,61,13) ;
    static final RGB CONSTANT_RGB = new RGB(36,37,134) ;
    static final RGB FUNCTION_RGB = new RGB(134,13,48) ;
    static final RGB COMMENT_RGB = new RGB(205,84,48) ;
  
//    Font textFont = new Font(Display.getCurrent(), "font", 14, 0);
    
    static final RGB BACKGROUND_RGB = new RGB(201,210,205) ;
    static final RGB FOREGROUND_RGB = new RGB(0,0,0) ;
    
    static final String COLOR_PREFIX = "color_" ;
    String PREF_KEYWORD_FG = 		COLOR_PREFIX + "keyword_fg" ;
    String PREF_EVENT_FG = 		COLOR_PREFIX + "event_fg" ;
    String PREF_TYPE_FG = 		COLOR_PREFIX + "type_fg" ;
    String PREF_STRING_FG = 		COLOR_PREFIX + "string_fg" ;
    String PREF_CONSTANT_FG = 	COLOR_PREFIX + "constant_fg" ;
    String PREF_FUNCTION_FG = 	COLOR_PREFIX + "function_fg" ;
    String PREF_COMMENT_FG = 		COLOR_PREFIX + "comment_fg" ;
    
    String PREF_INDENT_BRACE = 	"indent_braces" ;
    String PREF_FONT_BASIC = 		"font_basic" ;
    String PREF_FOREGROUND = 		"foreground" ;
    String PREF_BACKGROUND = 		"background" ;
    
    
    // updated 17Feb05 from wiki (++ default, state) (by hand)
    // http://secondlife.com/badgeo/wakka.php?wakka=FlowControl
    final static String[] KEYWORDS = {
    	    "default",
    	    "state",
    	    "for",
    	    "do",
    	    "while",
    	    "if",
   	    "else",
    	    "jump",
    	    "return",
        	} ;

    // updated 17Feb05 from wiki (by hand)
    // http://secondlife.com/badgeo/wakka.php?wakka=Types
    final static String[] TYPES = {
    	    "integer",
    	    "float",
    	    "string",
    	    "key",
    	    "vector",
    	    "rotation",
    	    "list",
        	} ;
    
     
    // updated 17Feb05 from wiki  (BBEdit of wakka=)
    // http://secondlife.com/badgeo/wakka.php?wakka=Events
    final static String[] EVENTS = {
    	    "at_rot_target",
    	    "at_target",
    	    "attach",
    	    "changed",
    	    "collision",
    	    "collision_end",
    	    "collision_start",
    	    "control",
    	    "dataserver",
    	    "email",
    	    "land_collision",
    	    "land_collision_end",
    	    "land_collision_start",
    	    "link_message",
    	    "listen",
    	    "money",
    	    "moving_end",
    	    "moving_start",
    	    "no_sensor",
    	    "not_at_rot_target",
    	    "not_at_target",
    	    "object_rez",
    	    "on_rez",
    	    "remote_data",
    	    "run_time_permissions",
    	    "sensor",
    	    "state_entry",
    	    "state_exit",
    	    "timer",
    	    "touch",
    	    "touch_end",
    	    "touch_start",
    	    } ;    
        

    // updated from wiki 17Feb05 (by hand).
    final static String[] CONSTANTS = {
            
// http://secondlife.com/badgeo/wakka.php?wakka=Constants            
            "PI",
            "TWO_PI",
            "PI_BY_TWO",
            "DEG_TO_RAD",
            "RAD_TO_DEG",
            "SQRT2",
            
            "TRUE",
            "FALSE",

            "NULL_KEY",
            "EOF",

            "ZERO_ROTATION",
            "ZERO_VECTOR",

            "AGENT",
            "ACTIVE",
            "PASSIVE",
            "SCRIPTED",

            
// http://secondlife.com/badgeo/wakka.php?wakka=llSetStatus       
            "STATUS_BLOCK_GRAB",
            "STATUS_DIE_AT_EDGE",
            "STATUS_PHANTOM",
            "STATUS_PHYSICS",
            "STATUS_RETURN_AT_EDGE",
            "STATUS_ROTATE_X",
            "STATUS_ROTATE_Y",
            "STATUS_ROTATE_Z",
            "STATUS_SANDBOX",

// http://secondlife.com/badgeo/wakka.php?wakka=llTakeControls
            "CONTROL_FWD",
            "CONTROL_BACK",
            "CONTROL_LEFT",
            "CONTROL_RIGHT",
            "CONTROL_ROT_LEFT",
            "CONTROL_ROT_RIGHT",
            "CONTROL_UP",
            "CONTROL_DOWN",
            "CONTROL_LBUTTON",
            "CONTROL_ML_LBUTTON",
            
// http://secondlife.com/badgeo/wakka.php?wakka=llGetPermissions
            "PERMISSION_DEBIT",
            "PERMISSION_TAKE_CONTROLS",
            "PERMISSION_TRIGGER_ANIMATION",
            "PERMISSION_ATTACH",
            "PERMISSION_CHANGE_LINKS",

// http://secondlife.com/badgeo/wakka.php?wakka=llGetAgentInfo
            "AGENT_FLYING",
            "AGENT_ATTACHMENTS",
            "AGENT_SCRIPTED",
            
// http://secondlife.com/badgeo/wakka.php?wakka=llParticleSystem 
	        	"PSYS_PART_BOUNCE_MASK",
	        	"PSYS_PART_EMISSIVE_MASK",
	        	"PSYS_PART_END_ALPHA",
	        	"PSYS_PART_END_COLOR",
	        	"PSYS_PART_END_SCALE",
	        	"PSYS_PART_FLAGS",
	        	"PSYS_PART_FOLLOW_SRC_MASK",
	        	"PSYS_PART_FOLLOW_VELOCITY_MASK",
	        	"PSYS_PART_INTERP_COLOR_MASK",
	        	"PSYS_PART_INTERP_SCALE_MASK",
	        	"PSYS_PART_MAX_AGE",
	        	"PSYS_PART_START_ALPHA",
	        	"PSYS_PART_START_COLOR",
	        	"PSYS_PART_START_SCALE",
	        	"PSYS_PART_TARGET_POS_MASK",
	        	"PSYS_PART_WIND_MASK",
	        	"PSYS_SRC_ACCEL",
	        	"PSYS_SRC_ANGLE_BEGIN",
	        	"PSYS_SRC_ANGLE_END",
	        	"PSYS_SRC_BURST_PART_COUNT",
	        	"PSYS_SRC_BURST_RADIUS",
	        	"PSYS_SRC_BURST_RATE",
	        	"PSYS_SRC_BURST_SPEED_MAX",
	        	"PSYS_SRC_BURST_SPEED_MIN",
	        	"PSYS_SRC_INNERANGLE",
	        	"PSYS_SRC_MAX_AGE",
	        	"PSYS_SRC_OMEGA",
	        	"PSYS_SRC_OUTERANGLE",
	        	"PSYS_SRC_PATTERN",
	        	"PSYS_SRC_PATTERN_ANGLE",
	        	"PSYS_SRC_PATTERN_ANGLE_CONE",
	        	"PSYS_SRC_PATTERN_DROP",
	        	"PSYS_SRC_PATTERN_EXPLODE",
	        	"PSYS_SRC_TARGET_KEY",
	        	"PSYS_SRC_TEXTURE",
            
// http://secondlife.com/badgeo/wakka.php?wakka=llSetVehicleType	        	
            "VEHICLE_TYPE_NONE",
            "VEHICLE_TYPE_AIRPLANE",
            "VEHICLE_TYPE_BALLOON",
            "VEHICLE_TYPE_BOAT",
            "VEHICLE_TYPE_CAR",
            "VEHICLE_TYPE_SLED",

            
// http://secondlife.com/badgeo/wakka.php?wakka=Vehicles           
            "VEHICLE_ANGULAR_DEFLECTION_EFFICIENCY",
            "VEHICLE_ANGULAR_DEFLECTION_TIMESCALE",
            "VEHICLE_ANGULAR_FRICTION_TIMESCALE",
            "VEHICLE_ANGULAR_MOTOR_DECAY_TIMESCALE",
            "VEHICLE_ANGULAR_MOTOR_DIRECTION",
            "VEHICLE_ANGULAR_MOTOR_TIMESCALE",
            "VEHICLE_BANKING_EFFICIENCY",
            "VEHICLE_BANKING_MIX",
            "VEHICLE_BANKING_TIMESCALE",
            "VEHICLE_BUOYANCY",            
            "VEHICLE_HOVER_EFFICIENCY",
            "VEHICLE_HOVER_HEIGHT",
            "VEHICLE_HOVER_TIMESCALE",
            "VEHICLE_LINEAR_DEFLECTION_EFFICIENCY",
            "VEHICLE_LINEAR_DEFLECTION_TIMESCALE",
            "VEHICLE_LINEAR_FRICTION_TIMESCALE",
            "VEHICLE_LINEAR_MOTOR_DECAY_TIMESCALE",
            "VEHICLE_LINEAR_MOTOR_DIRECTION",
            "VEHICLE_LINEAR_MOTOR_TIMESCALE",
            "VEHICLE_REFERENCE_FRAME",
            "VEHICLE_VERTICAL_ATTRACTION_EFFICIENCY",
            "VEHICLE_VERTICAL_ATTRACTION_TIMESCALE",

// http://secondlife.com/badgeo/wakka.php?wakka=llSetVehicleFlags
	        	"VEHICLE_FLAG_NO_DEFLECTION_UP",
	        	"VEHICLE_FLAG_LIMIT_ROLL_ONLY",
	        	"VEHICLE_FLAG_HOVER_WATER_ONLY",
	        	"VEHICLE_FLAG_HOVER_TERRAIN_ONLY",
	        	"VEHICLE_FLAG_HOVER_GLOBAL_HEIGHT",
	        	"VEHICLE_FLAG_HOVER_UP_ONLY",
	        	"VEHICLE_FLAG_LIMIT_MOTOR_UP",
	        	"VEHICLE_FLAG_MOUSELOOK_STEER",
	        	"VEHICLE_FLAG_MOUSELOOK_BANK",
	        	"VEHICLE_FLAG_CAMERA_DECOUPLED",


// http://secondlife.com/badgeo/wakka.php?wakka=llGetInventoryNumber         
	        	"INVENTORY_TEXTURE",
	        	"INVENTORY_SOUND",
	        	"INVENTORY_OBJECT",
	        	"INVENTORY_SCRIPT",
	        	"INVENTORY_LANDMARK",
	        	"INVENTORY_CLOTHING",
	        	"INVENTORY_BODYPART",
	        	"INVENTORY_NOTECARD",
	        	"INVENTORY_ANIMATION",
	        	"INVENTORY_GESTURE",
            
// http://secondlife.com/badgeo/wakka.php?wakka=llAttachToAvatar
	        	"ATTACH_LPEC",
	        	"ATTACH_HEAD",
	        	"ATTACH_LSHOULDER",
	        	"ATTACH_RSHOULDER",
	        	"ATTACH_LHAND",
	        	"ATTACH_RHAND",
	        	"ATTACH_LFOOT",
	        	"ATTACH_RFOOT",
	        	"ATTACH_BACK",
	        	"ATTACH_PELVIS",
	        	"ATTACH_MOUTH",
	        	"ATTACH_CHIN",
	        	"ATTACH_LEAR",
	        	"ATTACH_REAR",
	        	"ATTACH_LEYE",
	        	"ATTACH_REYE",
	        	"ATTACH_NOSE",
	        	"ATTACH_RUARM",
	        	"ATTACH_RLARM",
	        	"ATTACH_LUARM",
	        	"ATTACH_LLARM",
	        	"ATTACH_RHIP",
	        	"ATTACH_LHIP",
	        	"ATTACH_RULEG",
	        	"ATTACH_RLLEG",
	        	"ATTACH_LULEG",
	        	"ATTACH_LLLEG",
	        	"ATTACH_BELLY",
	        	"ATTACH_RPEC",
	        	"ATTACH_LPEC",

// http://secondlife.com/badgeo/wakka.php?wakka=llModifyLand	        	
            "LAND_LEVEL",
            "LAND_RAISE",
            "LAND_LOWER",
            "LAND_SMOOTH",
            "LAND_NOISE",
            "LAND_REVERT",
            "LAND_SMALL_BRUSH",
            "LAND_MEDIUM_BRUSH",
            "LAND_LARGE_BRUSH",
            
// http://secondlife.com/badgeo/wakka.php?wakka=llRequestAgentData
            "DATA_ONLINE",
            "DATA_NAME",
            "DATA_BORN",
            "DATA_RATING",
            
// http://secondlife.com/badgeo/wakka.php?wakka=llSetTextureAnim            
            "ANIM_ON",
            "LOOP",
            "REVERSE",
            "PING_PONG",
            "SMOOTH",
            "ROTATE",
            "SCALE",
            "ALL_SIDES",

// http://secondlife.com/badgeo/wakka.php?wakka=Link           
            "LINK_ROOT",
            "LINK_SET",
            "LINK_ALL_OTHERS",
            "LINK_ALL_CHILDREN",
            
// http://secondlife.com/badgeo/wakka.php?wakka=changed         
            "CHANGED_INVENTORY",
            "CHANGED_COLOR",
            "CHANGED_SHAPE",
            "CHANGED_SCALE",
            "CHANGED_TEXTURE",
            "CHANGED_LINK",
            "CHANGED_ALLOWED_DROP",

// http://secondlife.com/badgeo/wakka.php?wakka=llGetListEntryType            
            "TYPE_INTEGER",
            "TYPE_FLOAT",
            "TYPE_STRING",
            "TYPE_KEY",
            "TYPE_VECTOR",
            "TYPE_ROTATION",
            "TYPE_INVALID",

// http://secondlife.com/badgeo/wakka.php?wakka=llSetPrimitiveParams            
	        	"PRIM_BUMP_SHINY",
	        	"PRIM_COLOR",
	        	"PRIM_MATERIAL",
	        	"PRIM_PHANTOM",
	        	"PRIM_PHYSICS",
	        	"PRIM_POSITION",
	        	"PRIM_ROTATION",
	        	"PRIM_SIZE",
	        	"PRIM_TEMP_ON_REZ",
	        	"PRIM_TYPE",
	        	"PRIM_TEXTURE",
	        	"PRIM_TYPE_BOX",
	        	"PRIM_TYPE_CYLINDER",
	        	"PRIM_TYPE_PRISM",
	        	"PRIM_TYPE_SPHERE",
	        	"PRIM_TYPE_TORUS",
	        	"PRIM_TYPE_TUBE",
	        	"PRIM_TYPE_RING",
	        	"PRIM_HOLE_DEFAULT",
	        	"PRIM_HOLE_SQUARE",
	        	"PRIM_HOLE_CIRCLE",
	        	"PRIM_HOLE_TRIANGLE",
	        	"PRIM_BUMP_NONE",
	        	"PRIM_BUMP_BRIGHT",
	        	"PRIM_BUMP_DARK",
	        	"PRIM_BUMP_WOOD",
	        	"PRIM_BUMP_BARK",
	        	"PRIM_BUMP_BRICKS",
	        	"PRIM_BUMP_CHECKER",
	        	"PRIM_BUMP_CONCRETE",
	        	"PRIM_BUMP_TILE",
	        	"PRIM_BUMP_STONE",
	        	"PRIM_BUMP_DISKS",
	        	"PRIM_BUMP_GRAVEL",
	        	"PRIM_BUMP_BLOBS",
	        	"PRIM_BUMP_SIDING",
	        	"PRIM_BUMP_LARGETILE",
	        	"PRIM_BUMP_STUCCO",
	        	"PRIM_BUMP_SUCTION",
	        	"PRIM_BUMP_WEAVE",
	        	"PRIM_SHINY_NONE",
	        	"PRIM_SHINY_LOW",
	        	"PRIM_SHINY_MEDIUM",
	        	"PRIM_SHINY_HIGH",
	        	"PRIM_MATERIAL_STONE",
	        	"PRIM_MATERIAL_METAL",
	        	"PRIM_MATERIAL_GLASS",
	        	"PRIM_MATERIAL_WOOD",
	        	"PRIM_MATERIAL_FLESH",
	        	"PRIM_MATERIAL_PLASTIC",
	        	"PRIM_MATERIAL_RUBBER",
	        	"PRIM_MATERIAL_LIGHT",
     
//TODO:  other constants may be missing, check lslguide.html            
        	} ;

    // updated 17Feb05 from wiki (many new functions in 1.4++) (BBEdit wakka=)
    // http://secondlife.com/badgeo/wakka.php?wakka=Functions
    final static String[] FUNCTIONS = {
        	"llAbs",
        	"llAcos",
        	"llAddToLandPassList",
        	"llAdjustSoundVolume",
        	"llAllowInventoryDrop",
        	"llAngleBetween",
        	"llApplyImpulse",
        	"llApplyRotationalImpulse",
        	"llAsin",
        	"llAtan2",
        	"llAttachToAvatar",
        	"llAvatarOnSitTarget",
        	"llAxes2Rot",
        	"llAxisAngle2Rot",
        	"llBase64ToInteger",
        	"llBase64ToString",
        	"llBreakAllLinks",
        	"llBreakLink",
        	"llCSV2List",
        	"llCeil",
        	"llCloseRemoteDataChannel",
        	"llCloud",
        	"llCollisionFilter",
        	"llCollisionSound",
        	"llCollisionSprite",
        	"llCos",
        	"llCreateLink",
        	"llDeleteSubList",
        	"llDeleteSubString",
        	"llDetachFromAvatar",
        	"llDetectedGrab",
        	"llDetectedGroup",
        	"llDetectedKey",
        	"llDetectedLinkNumber",
        	"llDetectedName",
        	"llDetectedOwner",
        	"llDetectedPos",
        	"llDetectedRot",
        	"llDetectedType",
        	"llDetectedVel",
        	"llDialog",
        	"llDie",
        	"llDumpList2String",
        	"llEdgeOfWorld",
        	"llEjectFromLand",
        	"llEmail",
        	"llEuler2Rot",
        	"llFabs",
        	"llFloor",
        	"llFrand",
        	"llGetAccel",
        	"llGetAgentInfo",
        	"llGetAgentSize",
        	"llGetAlpha",
        	"llGetAndResetTime",
        	"llGetAnimation",
        	"llGetAnimationList",
        	"llGetAttached",
        	"llGetBoundingBox",
        	"llGetCenterOfMass",
        	"llGetCreator",
        	"llGetColor",
        	"llGetDate",
        	"llGetEnergy",
        	"llGetForce",
        	"llGetFreeMemory",
        	"llGetGeometricCenter",
        	"llGetGMTclock",
        	"llGetInventoryKey",
        	"llGetInventoryName",
        	"llGetInventoryNumber",
        	"llGetInventoryPermMask",
        	"llGetKey",
        	"llGetLandOwnerAt",
        	"llGetLinkKey",
        	"llGetLinkName",
        	"llGetLinkNumber",
        	"llGetListEntryType",
        	"llGetListLength",
        	"llGetLocalPos",
        	"llGetLocalRot",
        	"llGetMass",
        	"llGetNextEmail",
        	"llGetNotecardLine",
        	"llGetNumberOfNotecardLines",
        	"llGetNumberOfPrims",
        	"llGetNumberOfSides",
        	"llGetObjectDesc",
        	"llGetObjectName",
        	"llGetObjectPermMask",
        	"llGetOmega",
        	"llGetOwner",
        	"llGetOwnerKey",
        	"llGetPermissions",
        	"llGetPermissionsKey",
        	"llGetPos",
        	"llGetPrimitiveParams",
        	"llGetRegionCorner",
        	"llGetRegionFPS",
        	"llGetRegionName",
        	"llGetRegionTimeDilation",
        	"llGetRootPosition",
        	"llGetRootRotation",
        	"llGetRot",
        	"llGetScale",
        	"llGetScriptName",
        	"llGetScriptState",
        	"llGetSimulatorHostname",
        	"llGetStartParameter",
        	"llGetStatus",
        	"llGetSubString",
        	"llGetSunDirection",
        	"llGetTexture",
        	"llGetTextureOffset",
        	"llGetTextureRot",
        	"llGetTextureScale",
        	"llGetTime",
        	"llGetTimeOfDay",
        	"llGetTimestamp",
        	"llGetTorque",
        	"llGetVel",
        	"llGetWallclock",
        	"llGiveInventory",
        	"llGiveInventoryList",
        	"llGiveMoney",
        	"llGodLikeRezObject",
        	"llGround",
        	"llGroundContour",
        	"llGroundNormal",
        	"llGroundRepel",
        	"llGroundSlope",
        	"llInsertString",
        	"llInstantMessage",
        	"llIntegerToBase64",
        	"llKey2Name",
        	"llList2CSV",
        	"llList2Float",
        	"llList2Integer",
        	"llList2Key",
        	"llList2List",
        	"llList2ListStrided",
        	"llList2Rot",
        	"llList2String",
        	"llList2Vector",
        	"llListFindList",
        	"llListInsertList",
        	"llListRandomize",
        	"llListSort",
        	"llListen",
        	"llListenControl",
        	"llListenRemove",
        	"llLoadURL",
        	"llLog",
        	"llLog10",
        	"llLookAt",
        	"llLoopSound",
        	"llLoopSoundMaster",
        	"llLoopSoundSlave",
        	"llMakeExplosion",
        	"llMakeFire",
        	"llMakeFountain",
        	"llMakeSmoke",
        	"llMD5String",
        	"llMessageLinked",
        	"llMinEventDelay",
        	"llModifyLand",
        	"llMoveToTarget",
        	"llOffsetTexture",
        	"llOpenRemoteDataChannel",
        	"llOverMyLand",
        	"llParseString2List",
        	"llParseStringKeepNulls",
        	"llParticleSystem",
        	"llPassCollisions",
        	"llPassTouches",
        	"llPlaySound",
        	"llPlaySoundSlave",
        	"llPointAt",
        	"llPow",
        	"llPreloadSound",
        	"llPushObject",
        	"llReleaseCamera",
        	"llReleaseControls",
        	"llRemoteDataReply",
        	"llRemoteDataSetRegion",
        	"llRemoteLoadScript",
        	"llRemoteLoadScriptPin",
        	"llRemoveInventory",
        	"llRemoveVehicleFlags",
        	"llRequestAgentData",
        	"llRequestInventoryData",
        	"llRequestPermissions",
        	"llResetOtherScript",
        	"llResetScript",
        	"llResetTime",
        	"llRezAtRoot",
        	"llRezObject",
        	"llRot2Angle",
        	"llRot2Axis",
        	"llRot2Euler",
        	"llRot2Fwd",
        	"llRot2Left",
        	"llRot2Up",
        	"llRotBetween",
        	"llRotLookAt",
        	"llRotTarget",
        	"llRotTargetRemove",
        	"llRotateTexture",
        	"llRound",
        	"llSameGroup",
        	"llSay",
        	"llScaleTexture",
        	"llScriptDanger",
        	"llSendRemoteData",
        	"llSensor",
        	"llSensorRemove",
        	"llSensorRepeat",
        	"llSetAlpha",
        	"llSetBuoyancy",
        	"llSetCameraAtOffset",
        	"llSetCameraEyeOffset",
        	"llSetColor",
        	"llSetDamage",
        	"llSetForce",
        	"llSetForceAndTorque",
        	"llSetHoverHeight",
        	"llSetInventoryPermMask",
        	"llSetLinkAlpha",
        	"llSetLinkColor",
        	"llSetLocalRot",
        	"llSetObjectDesc",
        	"llSetObjectName",
        	"llSetObjectPermMask",
        	"llSetParcelMusicURL",
        	"llSetPos",
        	"llSetPrimitiveParams",
        	"llSetRemoteScriptAccessPin",
        	"llSetRot",
        	"llSetScale",
        	"llSetScriptState",
        	"llSetSitText",
        	"llSetSoundQueueing",
        	"llSetSoundRadius",
        	"llSetStatus",
        	"llSetText",
        	"llSetTexture",
        	"llSetTextureAnim",
        	"llSetTimerEvent",
        	"llSetTorque",
        	"llSetTouchText",
        	"llSetVehicleFlags",
        	"llSetVehicleFloatParam",
        	"llSetVehicleRotationParam",
        	"llSetVehicleType",
        	"llSetVehicleVectorParam",
        	"llShout",
        	"llSin",
        	"llSitTarget",
        	"llSleep",
        	"llSound",
        	"llSoundPreload",
        	"llSqrt",
        	"llStartAnimation",
        	"llStopAnimation",
        	"llStopHover",
        	"llStopLookAt",
        	"llStopMoveToTarget",
        	"llStopPointAt",
        	"llStopSound",
        	"llStringLength",
        	"llStringToBase64",
        	"llSubStringIndex",
        	"llTakeCamera",
        	"llTakeControls",
        	"llTan",
        	"llTarget",
        	"llTargetOmega",
        	"llTargetRemove",
        	"llTeleportAgentHome",
        	"llToLower",
        	"llToUpper",
        	"llTriggerSound",
        	"llTriggerSoundLimited",
        	"llUnSit",
        	"llVecDist",
        	"llVecMag",
        	"llVecNorm",
        	"llVolumeDetect",
        	"llWater",
        	"llWhisper",
        	"llWind",
        	"llXorBase64Strings",
        	} ;    

}
